### ISSUE TITLE
Adminer not working with SiteGround Security

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-client#9]
Adminer is by default not working when SiteGround Security is activated, can we solve this?

**Comment by remcotolsma** [comment]
https://plugins.trac.wordpress.org/browser/sg-security/tags/1.3.4/templates/directory-hardening.tpl

**Comment by rvdsteege** [comment]
We can hook into the allow list filter:
- https://plugins.trac.wordpress.org/browser/sg-security/tags/1.3.4/core/Htaccess_Service/Directory_Service.php#L93

```
// Add custom whitelist.
$this->types[ $this->type ]['whitelist'] = apply_filters( 'sgs_whitelist_wp_' . $this->type, $this->types[ $this->type ]['whitelist'] );
```

**Comment by remcotolsma** [comment]
Fixed in https://github.com/pronamic/wp-pronamic-client/commit/9344615cdd15ae55e4947ddfa3ee1c4ee6759ee2.
